### ISSUE TITLE
cannot use it with react version 17

### ISSUE THREAD

**Issue by SimaGhoreyshi** [alithecodeguy/iran-map#2]
here is the console error :

```
code ERESOLVE
ERESOLVE unable to resolve dependency tree

While resolving: name-of-my-project
Found: react@17.0.2
node_modules/react
  react@"^17.0.2" from the root project

Could not resolve dependency:
peer react@"^16.0.0" from iran-map@1.0.5
node_modules/iran-map
  iran-map@"*" from the root project
```

**Comment by SaeedPoureshghi** [comment]
#3 pull request submitted

**Comment by alithecodeguy** [comment]
@SaeedPoureshghi  fixed it.

> here is the console error :
> 
> ```
> code ERESOLVE
> ERESOLVE unable to resolve dependency tree
> 
> While resolving: name-of-my-project
> Found: react@17.0.2
> node_modules/react
>   react@"^17.0.2" from the root project
> 
> Could not resolve dependency:
> peer react@"^16.0.0" from iran-map@1.0.5
> node_modules/iran-map
>   iran-map@"*" from the root project
> ```

@SaeedPoureshghi  fixed it.
